version: '3.7'
services:
  sqlpad:
    container_name: sqlpad
    image: sqlpad/sqlpad:latest
    environment:
      - SQLPAD_ADMIN=admin
      - SQLPAD_ADMIN_PASSWORD=admin
    ports:
      - "33000:3000"