version: "3.7"
services:
  questdb:
    container_name: questdb
    image: questdb/questdb
    volumes:
      - ./data/:/root/.questdb
    ports:
      - "9009:9009"
      - "8812:8812"
      - "9003:9003"
      - "9000:9000"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
        reservations:
          memory: 4096M
    networks:
      - default
networks:
  default: