version: "3.7"
services:
  dorisdb:
    container_name: dorisdb
    image: apachedoris/doris-dev:build-env-1.3
    volumes:
      - ./data/:/root/incubator-doris-DORIS-1.3-release/
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4096M
        reservations:
          memory: 4096M
    networks:
      - default
networks:
  default: